# docker-compose -f docker-compose-dev.yaml up -d --build
# docker-compose -f docker-compose-dev.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../
      dockerfile: ./workflow-array-ephys/Dockerfile.dev
    env_file: .env
    image: workflow_array_ephys_dev:0.1.0a4
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../element-lab:/main/element-lab
      - ../element-animal:/main/element-animal
      - ../element-session:/main/element-session
      - ../element-array-ephys:/main/element-array-ephys
      - .:/main/workflow-array-ephys
    depends_on:
      db:
        condition: service_healthy
networks:
  main: